name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build-all:
    runs-on:
      - machine
      - gpu=l40s
      - tenancy=spot
      - cpu=4
      - ram=32
      - architecture=x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image_server Docker image
        uses: docker/build-push-action@v6.11.0
        with:
          file: Dockerfile.image_server
          push: false
          build-args: |
            CONDA_PLUGINS_AUTO_ACCEPT_TOS=true

      - name: Build orchestrator Docker image
        uses: docker/build-push-action@v6.11.0
        with:
          file: Dockerfile.orchestrator
          push: false
          build-args: |
            CONDA_PLUGINS_AUTO_ACCEPT_TOS=true
